### ISSUE TITLE
No module named 'toml'    and      from omni.isaac.lab.app import AppLauncherError: No module named 'omni.isaac.lab'

### ISSUE THREAD

**Issue by Xuegegeupupup** [orbit-surgical/orbit-surgical#22]
1 when I run 
From within the ORBIT-Surgical directory, install ORBIT-Surgical:
    ./orbitsurgical.sh

it would occur the error report as 
      ModuleNotFoundError: No module named 'toml'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

2 when I bypass the first question, when run the command in  ORBIT-Surgical directory
${IsaacLab_PATH}/isaaclab.sh -p source/standalone/environments/list_envs.py
it would report a error as

  from omni.isaac.lab.app import AppLauncher
ModuleNotFoundError: No module named 'omni.isaac.lab'

my system is ubuntu 20.04, did you ever solve the error as I mention over? I would appreciate it if you could give me some instruction.

Thanks a lot

**Comment by ZhangErliCarl** [comment]
hi encountered the same issues did you manage to solve it?

**Comment by savitha-suresh** [comment]
Orbit surgical is written using an old version of isaac -lab , before 2.0.0. Isaaclab changed the package structure. 
https://gist.github.com/kellyguo11/3e8f73f739b1c013b1069ad372277a85

You can use this file to rename the packages in orbit-surgical. It works.

**Comment by snowflake250** [comment]
> Orbit surgical is written using an old version of isaac -lab , before 2.0.0. Isaaclab changed the package structure. https://gist.github.com/kellyguo11/3e8f73f739b1c013b1069ad372277a85
> 
> You can use this file to rename the packages in orbit-surgical. It works.

Hello, may I ask which version of Isaaclab and IsaacSim is the most suitable? I'm having trouble choosing the version.

**Comment by savitha-suresh** [comment]
> > Orbit surgical is written using an old version of isaac -lab , before 2.0.0. Isaaclab changed the package structure. https://gist.github.com/kellyguo11/3e8f73f739b1c013b1069ad372277a85
> > You can use this file to rename the packages in orbit-surgical. It works.
> 
> Hello, may I ask which version of Isaaclab and IsaacSim is the most suitable? I'm having trouble choosing the version.

If you run the rename script mentioned, you can use Isaaclab v2.1.0 and IsaacSim 4.5.0 ( both latest) without any issues. There is a bit of problem with exporting the trained policy if you are using rl from orbit-surgical but i am assuming that is not a blocker.

**Comment by snowflake250** [comment]
> > > Orbit surgical is written using an old version of isaac -lab , before 2.0.0. Isaaclab changed the package structure. https://gist.github.com/kellyguo11/3e8f73f739b1c013b1069ad372277a85
> > > You can use this file to rename the packages in orbit-surgical. It works.
> > 
> > 
> > Hello, may I ask which version of Isaaclab and IsaacSim is the most suitable? I'm having trouble choosing the version.
> 
> If you run the rename script mentioned, you can use Isaaclab v2.1.0 and IsaacSim 4.5.0 ( both latest) without any issues. There is a bit of problem with exporting the trained policy if you are using rl from orbit-surgical but i am assuming that is not a blocker.

Thank you very much for your reply. I do intend to use rl and export the trained strategy. Which version of ISAACLAB and ISAACSIM is more suitable for this situation? Are isaaclab1.4.0 and isaacsim4.2 suitable choices?

**Comment by savitha-suresh** [comment]
@snowflake250 I havent tried with older versions but from reading the documentation and package structure i thin isaaclab 1.4.0 and isaacsim 4.1.0 should work. 

PS: Rl training works with latest version, I am guessing its a small bug for exporting which can also be fixed. Maybe you can try to fix the bug in rsl_rl/play.py , I am saying because fixing the bug should be easier than working with old versions. 

Edit:

https://github.com/orbit-surgical/orbit-surgical/pull/23/
Please check this PR. I have fixed the bug and I am able to train and play 'Lift the block' task using rsl_rl using latest version of isaaclab and isaacsim

**Comment by Xuegegeupupup** [comment]
@savitha-suresh Thanks for your instruction, I have solved the problem by rename the packages in orbit-surgical.
@ZhangErliCarl  you can also take the advice as mentioned before

**Comment by BodongDu** [comment]
![Image](https://github.com/user-attachments/assets/51bd2fec-143f-4d86-a170-96a23c6cebc8)

![Image](https://github.com/user-attachments/assets/bbc60f3e-9257-473f-b4ba-37672f909701)

I have run the rename.py file, however it still fail to run orbitsugrical.sh file, how can I fix it? I use the newest Isaac Lab and Isaac Sim

**Comment by BodongDu** [comment]
@Xuegegeupupup Are you using this code https://gist.github.com/kellyguo11/3e8f73f739b1c013b1069ad372277a85 to rename the orbit-sugrical file? I change the line 43 root_directory = 'source' to the path of orbit-surgical and rename it. Then I run the orbitsurgical.sh but still fail. Could you share your process for me? Thanks!

**Comment by BodongDu** [comment]
@savitha-suresh Could you please tell me how to handle this situation? Thanks a lot!

**Comment by nicolapiccinelli** [comment]
Hello everybody, I've managed to install the dependencies via `orbitsurgical.sh` by modifying the script like this:

```
#!/usr/bin/env bash

# Copyright (c) 2024, The ORBIT-Surgical Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

${IsaacLab_PATH}/isaaclab.sh -p -m pip install --no-build-isolation -e source/extensions/orbit.surgical.ext
${IsaacLab_PATH}/isaaclab.sh -p -m pip install --no-build-isolation -e source/extensions/orbit.surgical.assets
${IsaacLab_PATH}/isaaclab.sh -p -m pip install --no-build-isolation -e source/extensions/orbit.surgical.tasks
```

**Comment by savitha-suresh** [comment]
> [@savitha-suresh](https://github.com/savitha-suresh) Could you please tell me how to handle this situation? Thanks a lot!

Hey
I missed this. Were you able to get it running?
